version: '3.8'
services:
  angular-app:
    build:
      context: ..
    ports:
      - "4200:4200"
    volumes:
      - ../:/app
      - /app/node_modules

networks:
  abc-call-network:
    external: true