name: Integration
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.0.0'
      - name: Install dependencies
        run: |
          npm install
          npm install -g @angular/cli@18.1.4
      - name: Run tests
        run: |
          ng test --code-coverage
  merge-branches:
    name: Merge Master into Develop and Develop into Master
    runs-on: ubuntu-latest
    needs: run-tests
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'terminada') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge master into develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: master
          target-branch: develop
          merge-method: no-ff

      - name: Merge develop into master
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: master
          merge-method: no-ff
